baseurl = "https://www.lvguowei.me/"
languageCode = "en-us"
title = "Guowei Lv"
theme = "future-imperfect"
preserveTaxonomyNames = true
pygmentsuseclasses = true
canonifyurls = true
disqusShortname = "lvguoweime"
googleAnalytics = "UA-71831707-2"
paginate = 5
enableRobotsTXT = true
canonifyURLs = true


[params]
    # Sets the meta tag description, usually reserved for the main page
    description          = "Guowei Lv"
    # This will appear on the top left of the navigation bar
    navbarTitle          = "Guowei Lv"
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = true
    # set this to the section name if section is not post
    #viewMorePostLink     = "/post/"

# Optional Params
    categoriesByCount    = true
    includeReadingTime   = true
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = true
    faviconVersion       = ""

    # Load custom CSS or JavaScript files. This replaces the deprecated params
    # minifiedFilesCSS and minifiedFilesJS. The variable is an array so that you
    # can load multiple files if necessary. You can also load the standard theme
    # files by adding the value, "default".
    # customCSS            = ["default", "/path/to/file"]
    # customJS             = ["default", "/path/to/file"]

    # Loading min files for exampleSite
    #customCSS            = ["default", "/css/main.min.css"]
    #customJS             = ["default", "/js/main.min.js"]

# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "Guowei Lv"

    paragraph = "Thinker · Writer · Coder · Painter"

    about     = "Welcome to my personal website. In here, I talk about programming in general and other cool stuff. Stay tuned!"

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.intro.pic]
    src       = "/img/logo.jpg"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = false
    imperfect = true
    width     = ""
    alt       = "Guowei Lv"

# Adjust the amount of recent posts on the sidebar.
# This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 5

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text
[[menu.main]]
    name = "Blog"
    url = "/post"
    identifier = "fa fa-newspaper-o"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "/categories"
    identifier = "fa fa-folder-open-o"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    identifier = "fa fa-user"
    weight = 3

# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[social]
    github          = "lvguowei"
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = "lvguowei"
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "lvguowei"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = "lvguowei"
    pinterest       = ""
    googleplus      = ""
    facebook        = "lvguowei"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "lvguowei1002"
    email           = "lvguowei1002@gmail.com"
